# Generated by Django 4.2.5 on 2024-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_moviecomment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='temporary_field',
            field=models.BooleanField(default=False),
        ),
    ]
