# Generated by Django 4.2.5 on 2024-01-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_movie_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
