# Generated by Django 4.2.5 on 2024-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='temporary_field',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cat',
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ManyToManyField(to='films.category'),
        ),
    ]
