# Generated by Django 4.2.5 on 2024-01-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_movie_temporary_field_remove_movie_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cat',
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.category'),
        ),
    ]
